/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class inicios extends javax.swing.JFrame {

    /**
     * Creates new form inicios
    */
    
    registrar panel1;
    consultar panel2;
    editar panel3;
    eliminar panel4;
    detectives panel5;
    
    public inicios() {
        initComponents();
        this.setLocationRelativeTo(null);
        panel1= new registrar();
        panel2 = new consultar();
        panel3 = new editar();
        panel4 = new eliminar();
        panel5 = new detectives();
    }
    
    
    public void run() {
        new inicios().setVisible(true); 
    }
    
    public void limpiarTabla(DefaultTableModel modelo_tabla) {
        int a = modelo_tabla.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            modelo_tabla.removeRow(modelo_tabla.getRowCount() - 1);
            
            //cargaTicket();
        }
    }
    
    private void pasarpanel(JPanel p)
    {
        
      fondo1.setVisible(true);
      fondo.setVisible(false);
      
      p.setSize(830, 620);
      p.setLocation(0, 0);
      
      fondo1.removeAll();
      fondo1.add(p, BorderLayout.CENTER);
      fondo1.revalidate();
      fondo1.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        fondo1 = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        registrar = new javax.swing.JButton();
        consultarcas = new javax.swing.JButton();
        consultardec = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();

        jButton3.setText("jButton1");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setLocationByPlatform(true);
        setUndecorated(true);

        fondo1.setBackground(new java.awt.Color(153, 153, 153));
        fondo1.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout fondo1Layout = new javax.swing.GroupLayout(fondo1);
        fondo1.setLayout(fondo1Layout);
        fondo1Layout.setHorizontalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        fondo1Layout.setVerticalGroup(
            fondo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        fondo.setBackground(new java.awt.Color(153, 153, 153));
        fondo.setForeground(new java.awt.Color(255, 255, 153));
        fondo.setRequestFocusEnabled(false);
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("OFICINA");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 110, 40));

        editar.setBackground(new java.awt.Color(204, 0, 204));
        editar.setForeground(new java.awt.Color(0, 0, 0));
        editar.setText("EDITAR CASOS");
        editar.setBorder(null);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        fondo.add(editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 160, 50));

        registrar.setBackground(new java.awt.Color(255, 51, 51));
        registrar.setForeground(new java.awt.Color(0, 0, 0));
        registrar.setText("REGISTRAR CASOS");
        registrar.setBorder(null);
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });
        fondo.add(registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 160, 50));

        consultarcas.setBackground(new java.awt.Color(0, 0, 255));
        consultarcas.setForeground(new java.awt.Color(0, 0, 0));
        consultarcas.setText("CONSULTAR CASOS");
        consultarcas.setBorder(null);
        consultarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarcasActionPerformed(evt);
            }
        });
        fondo.add(consultarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 160, 50));

        consultardec.setBackground(new java.awt.Color(0, 153, 153));
        consultardec.setForeground(new java.awt.Color(0, 0, 0));
        consultardec.setText("CONSULTAR DETECTIVES");
        consultardec.setBorder(null);
        consultardec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultardecActionPerformed(evt);
            }
        });
        fondo.add(consultardec, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 160, 50));

        salir.setBackground(new java.awt.Color(204, 204, 0));
        salir.setForeground(new java.awt.Color(0, 0, 0));
        salir.setText("SALIR");
        salir.setBorder(null);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        fondo.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 160, 50));

        eliminar.setBackground(new java.awt.Color(51, 255, 51));
        eliminar.setForeground(new java.awt.Color(0, 0, 0));
        eliminar.setText("ELIMINAR CASOS");
        eliminar.setBorder(null);
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        fondo.add(eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 160, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(fondo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    
    
    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
  
        pasarpanel(panel1);
      
    }//GEN-LAST:event_registrarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        pasarpanel(panel4);
        
        limpiarTabla(panel4.tabla);
        
        panel4.datosText();
    }//GEN-LAST:event_eliminarActionPerformed

    private void consultardecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultardecActionPerformed
        pasarpanel(panel5);
        
    }//GEN-LAST:event_consultardecActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void consultarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarcasActionPerformed
        pasarpanel(panel2);
        
        limpiarTabla(panel2.tabla);
        
        panel2.datosText();
    }//GEN-LAST:event_consultarcasActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        pasarpanel(panel3);
        limpiarTabla(panel3.tabla);
        
        panel3.datosText();
    }//GEN-LAST:event_editarActionPerformed

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarcas;
    private javax.swing.JButton consultardec;
    private javax.swing.JButton editar;
    private javax.swing.JButton eliminar;
    public static javax.swing.JPanel fondo;
    public static javax.swing.JPanel fondo1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registrar;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

}
