/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.FileWriter;
import java.io.IOException;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.CASOS.Casos_1;
import modelo.CASOS.cibercrimen;
import modelo.CASOS.homicidio;
import modelo.CASOS.narcotrafico;
import modulo.ListaCasos;
import static vista.registrar.casos;

/**
 *
 * @author asus
 */
public class registrar extends javax.swing.JPanel {

    /**
     * Creates new form registrar
     */
    public static ListaCasos modelo;
    public static Casos_1 casos;
    FileWriter salvar;
    
    
    public registrar() {
        initComponents();
        modelo = new ListaCasos();
        
    }
    

    public void registrarCasos() {
        Casos_1 nuevoCasos = this.leerNuevoCasos();
        modelo.insertarCasos(nuevoCasos);
    }
    
    public Casos_1 leerNuevoCasos() {
            try
            {
                int codig = Integer.parseInt(codigo.getText());
                String tip1 = (String) tipo.getSelectedItem();
                String descri = descripcion.getText();
                String prioridad = (String) priori.getSelectedItem();
                String nombreclave = nomclave.getText();
                String fech = fecha.getText();
                String obse = observacion.getText();
                int detec = tipo.getSelectedIndex();
                
                if(tip1 == "homicidio")
                {
                    casos = new homicidio(codig,tip1,descri,prioridad,nombreclave,fech,obse);
                }
                if (tip1 == "cibercrimen") {
                    panelaviso.setVisible(true);
                    String asoci = asociacion.getText();
                    casos = new cibercrimen(asoci,codig,tip1,descri,prioridad,nombreclave,fech,obse);
                }
                if (tip1 == "narcotrafico") {
                    String asoci = (String) tipo2.getSelectedItem();
                    casos = new narcotrafico(asoci,codig,tip1,descri,prioridad,nombreclave,fech,obse);
                }
                
                if(detec == 0)
                {
                    JOptionPane.showMessageDialog(null, "escoja un detective");
                }
                
            }catch(java.lang.NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "llene todos los campos");
                codigo.setText("");
                tipo.setSelectedIndex(0);
                auxi.setSelectedIndex(0);
                asociacion.setText("");
                tipo2.setSelectedIndex(0);
                descripcion.setText("");
                priori.setSelectedIndex(0);
                nomclave.setText("");
                fecha.setText("");
                observacion.setText("");
                
            }
        
        return casos;
    }
    
    public void textCasos() {

        try {
            salvar = new FileWriter("Casos.txt");
            List<Casos_1> lista = modelo.leerCasos();
            for (Casos_1 p : lista) {
                salvar.write(p.getDataStringFormat());
            }

            salvar.close();
        } catch (IOException x) {
            JOptionPane.showMessageDialog(null, "error");
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();
        asoci = new javax.swing.JPanel();
        auxi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        asociacion = new javax.swing.JTextField();
        señuelo = new javax.swing.JPanel();
        auxiliar = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        panelaviso = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        narcotrafico = new javax.swing.JPanel();
        tipo2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        descripcion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priori = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        nomclave = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        observacion = new javax.swing.JTextField();
        detectives = new javax.swing.JComboBox<>();
        sospechosos = new javax.swing.JComboBox<>();
        atras = new javax.swing.JButton();
        limpiar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setForeground(new java.awt.Color(0, 0, 0));

        panel1.setBackground(new java.awt.Color(102, 102, 102));
        panel1.setForeground(new java.awt.Color(255, 51, 51));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("codigo del caso");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("REGISTRAR CASOS");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 180, 40));

        codigo.setBackground(new java.awt.Color(204, 204, 204));
        codigo.setForeground(new java.awt.Color(0, 0, 0));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codigoKeyTyped(evt);
            }
        });
        panel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 120, 30));

        tipo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tipo.setForeground(new java.awt.Color(0, 255, 255));
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione", "cibercrimen", "narcotrafico", "homicidio" }));
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        panel1.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 130, 30));

        asoci.setBackground(new java.awt.Color(102, 102, 102));
        asoci.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        auxi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        auxi.setForeground(new java.awt.Color(255, 255, 255));
        auxi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "auxiliar", "jose corzo", "adalberto luthor", "carlos barraza", "jose ortiz" }));
        auxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auxiActionPerformed(evt);
            }
        });
        asoci.add(auxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 160, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("asociacion");
        asoci.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 20));

        asociacion.setBackground(new java.awt.Color(255, 255, 255));
        asociacion.setForeground(new java.awt.Color(0, 0, 0));
        asociacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asociacionActionPerformed(evt);
            }
        });
        asoci.add(asociacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 44, 110, 30));

        panel1.add(asoci, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 180, 110));

        señuelo.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout señueloLayout = new javax.swing.GroupLayout(señuelo);
        señuelo.setLayout(señueloLayout);
        señueloLayout.setHorizontalGroup(
            señueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        señueloLayout.setVerticalGroup(
            señueloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        panel1.add(señuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 200, 120));

        auxiliar.setBackground(new java.awt.Color(102, 102, 102));
        auxiliar.setForeground(new java.awt.Color(153, 153, 153));
        auxiliar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "local", "estatal", "internacional" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        auxiliar.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 25, 153, -1));

        panel1.add(auxiliar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, 190, -1));

        panelaviso.setBackground(new java.awt.Color(102, 102, 102));
        panelaviso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("detective auxiliar.");
        panelaviso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 148, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("se le asignara un");
        panelaviso.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        panel1.add(panelaviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 200, 90));

        narcotrafico.setBackground(new java.awt.Color(102, 102, 102));
        narcotrafico.setForeground(new java.awt.Color(153, 153, 153));

        tipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "estatal", "local", "internacional" }));

        javax.swing.GroupLayout narcotraficoLayout = new javax.swing.GroupLayout(narcotrafico);
        narcotrafico.setLayout(narcotraficoLayout);
        narcotraficoLayout.setHorizontalGroup(
            narcotraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(narcotraficoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        narcotraficoLayout.setVerticalGroup(
            narcotraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, narcotraficoLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(tipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        panel1.add(narcotrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 180, 100));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("descripcion");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        descripcion.setBackground(new java.awt.Color(204, 204, 204));
        descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripcionActionPerformed(evt);
            }
        });
        descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripcionKeyTyped(evt);
            }
        });
        panel1.add(descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 120, 30));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("prioridad");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 100, -1));

        priori.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        priori.setForeground(new java.awt.Color(0, 204, 204));
        priori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione", "A: poca", "B: moderada", "C: relevnate" }));
        priori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioriActionPerformed(evt);
            }
        });
        panel1.add(priori, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 130, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("nombre clave");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        nomclave.setBackground(new java.awt.Color(204, 204, 204));
        nomclave.setForeground(new java.awt.Color(0, 0, 0));
        panel1.add(nomclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 140, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("fecha");
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        fecha.setBackground(new java.awt.Color(204, 204, 204));
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });
        fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechaKeyTyped(evt);
            }
        });
        panel1.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 140, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("observacion");
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        observacion.setBackground(new java.awt.Color(204, 204, 204));
        observacion.setForeground(new java.awt.Color(0, 0, 0));
        observacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                observacionActionPerformed(evt);
            }
        });
        panel1.add(observacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 140, 30));

        detectives.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        detectives.setForeground(new java.awt.Color(0, 255, 255));
        detectives.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "detectives", "jay greison", "vanessa torres", "camilo lopez", "juan guerrera" }));
        panel1.add(detectives, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 160, 30));

        sospechosos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sospechosos.setForeground(new java.awt.Color(0, 255, 255));
        sospechosos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sospechosos", "wilkar muñoz", "manuel amaya", "jose garcia", "laura ramos" }));
        sospechosos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sospechososActionPerformed(evt);
            }
        });
        panel1.add(sospechosos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 309, 160, 30));

        atras.setBackground(new java.awt.Color(51, 255, 255));
        atras.setForeground(new java.awt.Color(0, 0, 0));
        atras.setText("ATRAS");
        atras.setBorder(null);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        panel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, 140, 60));

        limpiar1.setBackground(new java.awt.Color(102, 255, 102));
        limpiar1.setForeground(new java.awt.Color(0, 0, 0));
        limpiar1.setText("LIMPIAR");
        limpiar1.setBorder(null);
        limpiar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                limpiar1MouseClicked(evt);
            }
        });
        limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar1ActionPerformed(evt);
            }
        });
        panel1.add(limpiar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 130, 60));

        jButton1.setBackground(new java.awt.Color(255, 204, 0));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("GUARDAR");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 130, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaActionPerformed

    private void observacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_observacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_observacionActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        if(tipo.getSelectedItem().equals("homicidio"))
        {
            asoci.setVisible(false);
            panelaviso.setVisible(true);
            auxiliar.setVisible(true);
            narcotrafico.setVisible(false);
            señuelo.setVisible(false);
        }
        if(tipo.getSelectedItem().equals("cibercrimen"))
        {
            asoci.setVisible(true);
            panelaviso.setVisible(false);
            asoci.setVisible(true);
            narcotrafico.setVisible(false);
            señuelo.setVisible(true);
        }
        if(tipo.getSelectedItem().equals("narcotrafico"))
        {
            panelaviso.setVisible(false);
            asoci.setVisible(false);
            narcotrafico.setVisible(true);
            señuelo.setVisible(true);
        }
        /* if(selectipo.getSelectedItem().equals("audio libro"))
        {    
            panellibro.setVisible(false);
            panelaudiolibro.setVisible(true);
        }
        if(selectipo.getSelectedItem().equals("libro"))
        {
            panellibro.setVisible(true);
            panelaudiolibro.setVisible(false);
        }*/        
        
    }//GEN-LAST:event_tipoActionPerformed

    private void prioriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prioriActionPerformed

    private void descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripcionActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        inicios.fondo1.setVisible(false);
        inicios.fondo.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void limpiar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_limpiar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_limpiar1MouseClicked

    private void limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar1ActionPerformed
                codigo.setText("");
                tipo.setSelectedIndex(0);
                auxi.setSelectedIndex(0);
                asociacion.setText("");
                tipo2.setSelectedIndex(0);
                descripcion.setText("");
                priori.setSelectedIndex(0);
                nomclave.setText("");
                fecha.setText("");
                observacion.setText("");
    }//GEN-LAST:event_limpiar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        leerNuevoCasos();
        registrarCasos();
        textCasos();
        
                /*codigo.setText("");
                tipo.setSelectedIndex(0);
                auxi.setSelectedIndex(0);
                asociacion.setText("");
                tipo2.setSelectedIndex(0);
                descripcion.setText("");
                priori.setSelectedIndex(0);
                nomclave.setText("");
                fecha.setText("");
                observacion.setText("");*/
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codigoKeyTyped
        char validar = evt.getKeyChar();
        
        if (Character.isLetter(validar))
        {
            getToolkit().beep();
            evt.consume();
            
            JOptionPane.showMessageDialog(this, "solo numeros");
        }
    }//GEN-LAST:event_codigoKeyTyped

    private void fechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechaKeyTyped
         int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;
        boolean espacio = key == 32;

        if (!(numeros || espacio)) {
            evt.consume();
        }
    }//GEN-LAST:event_fechaKeyTyped

    private void descripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionKeyTyped
        int key = evt.getKeyChar();

        boolean mayusculas = key >= 65 && key <= 90;
        boolean minusculas = key >= 97 && key <= 122;

        if (!(minusculas || mayusculas)) {
            evt.consume();
        }
    }//GEN-LAST:event_descripcionKeyTyped

    private void sospechososActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sospechososActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sospechososActionPerformed

    private void auxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auxiActionPerformed

    private void asociacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asociacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asociacionActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel asoci;
    private javax.swing.JTextField asociacion;
    private javax.swing.JButton atras;
    private javax.swing.JComboBox<String> auxi;
    private javax.swing.JPanel auxiliar;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField descripcion;
    private javax.swing.JComboBox<String> detectives;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton limpiar1;
    private javax.swing.JPanel narcotrafico;
    private javax.swing.JTextField nomclave;
    private javax.swing.JTextField observacion;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panelaviso;
    private javax.swing.JComboBox<String> priori;
    private javax.swing.JPanel señuelo;
    private javax.swing.JComboBox<String> sospechosos;
    private javax.swing.JComboBox<String> tipo;
    private javax.swing.JComboBox<String> tipo2;
    // End of variables declaration//GEN-END:variables
}
